#!/usr/bin/env node

/*
  Create an EBS snapshot of [volume] that will expire in [days]
*/

var Awstk = require('../lib/awstk.js')
  , Optionall = require('optionall')
  , Path = require('path')
  , _ = require('underscore')
  , O = new Optionall({'__dirname': Path.normalize(require.main.filename + '/../..')});
;

O.aws = _.defaults(O.aws || {}, {
      'accessKeyId': O.AMAZON_KEY
    , 'secretAccessKey': O.AMAZON_SECRET
    , 'region': O.AMAZON_REGION
    });

var EC2 = new Awstk.ec2(O.aws);

if (O.h || O.help || O.usage || !O.volume){
  console.log('Create an EBS snapshot of [volume] that will expire in [days]');
  console.log('usage: --volume [volume id to backup] --days [days to retain snapshot]');
  process.exit(0);
}

EC2.createExpiringSnapshot(O.volume, O.days, function(err){
  if (err) console.error(err);
  return process.exit(err ? 1 : 0);
});
